---
name: ci
on: [push]
jobs:
  static-analysis:
    name: Run static analysis
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3
    - name: Setup | Prerequisites
      run: "sudo bash -c 'apt update && DEBIAN_FRONTEND=noninteractive apt install -y curl'"
    - name: Setup | Rust
      run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    - name: Setup | Rust Nightly
      run: "rustup install nightly"
    - name: Setup | Code Formatter
      run: "rustup update && rustup component add rustfmt"
    - name: Setup | Linter
      run: "rustup update && rustup component add clippy"
    - name: Code Format Check | App
      run: "cargo +nightly fmt -- --check --config-path src/"
    - name: Lint | App
      run: "cargo clippy -- -D warnings"

  build:
    needs: static-analysis
    name: Build and run small tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3
    - name: Setup | Prerequisites
      run: "sudo bash -c 'apt update && DEBIAN_FRONTEND=noninteractive apt install -y curl'"
    - name: Setup | Rust
      run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
    - name: Setup | Rust Nightly
      run: "rustup install nightly"
    - name: Setup | LLVM Tooling
      run: "rustup component add llvm-tools-preview"
    - name: Setup | LLVM helper
      run: "cargo install cargo-binutils && rustup component add llvm-tools-preview"
    - name: Build | App - Release
      run: "cargo build --release"
    - name: Build | App - Debug
      run: "LLVM_PROFILE_FILE='profiler_output.profraw' RUSTFLAGS='-C instrument-coverage' cargo build"
    - name: Small tests | App
      run: './.github/workflows/test_with_coverage.bash "$(pwd)" &> ./small_test_coverage_report.txt && cat ./small_test_coverage_report.txt'
    - name: Cache code coverage report | App
      uses: actions/cache@v3
      with:
        path: small_test_coverage_report.txt
        key: small_test_coverage_report-${{ github.ref }}
    - name: Cache debug output | App
      uses: actions/cache@v3
      with:
        path: target/debug/breadlog
        key: target-debug-breadlog-${{ github.ref }}
    - name: Cache release output | App
      uses: actions/cache@v3
      with:
        path: target/release/breadlog
        key: target-release-breadlog-${{ github.ref }}
